language: objective-c
osx_image: xcode9.3
xcode_sdk: iphonesimulator11.3
xcode_project: ImageCoordinateSpace.xcodeproj
xcode_scheme: ImageCoordinateSpace
before_install:
  - carthage version
  - bundle -v || gem install bundler
bundler_args: --no-deployment --without development
cache:
  bundler: true
  directories:
    - Carthage
before_script:
  - carthage outdated | grep "dependencies are outdated" -q && carthage update --platform iOS
  - git diff --exit-code # Outdated Carthage dependencies found, please run 'carthage update' and checkin changes
  - bundle update
  - git diff --exit-code # Outdated Bundle dependencies found, please run 'bundle update' and checkin changes
script:
  - set -o pipefail && pod lib lint --verbose | xcpretty || pod lib lint --verbose --no-clean
  - set -o pipefail && xcodebuild test -scheme "$TRAVIS_XCODE_SCHEME" -destination "platform=iOS Simulator,name=iPhone X" | xcpretty -f `xcpretty-travis-formatter` # generate coverage
after_success:
  - bash <(curl -s 'https://codecov.io/bash') -Z -J '^ImageCoordinateSpace$' -X gcov -X fix
after_failure:
  - echo "Random seed $( < /tmp/RandomTestable.Type.seed.txt)"
before_deploy:
  - pod lib lint
  - brew update > /dev/null
  - brew outdated carthage || brew upgrade carthage
  - carthage build --no-skip-current --platform iOS
  - carthage archive "$TRAVIS_XCODE_SCHEME"
deploy:
  provider: releases
  prerelease: true
  name: "Release $TRAVIS_TAG"
  body: "Travis build: https://travis-ci.org/${TRAVIS_REPO_SLUG}/jobs/${TRAVIS_JOB_ID} started by ${TRAVIS_EVENT_TYPE}"
  skip_cleanup: true
  api_key:
    secure: 'I2PLnV+L3TiDPlUpgXQNl0AQ1kyFzK1O5W1u1Htk84xl9y2jKgCm+t+7hklcZtZYA9etxtGtnPoxj3vzlfrqV2QwRfMksI+JTrloaDRV4KE2JDuDqb6/gEwAVjRcAANsiCYskq+PKhJBHQk1x//4UJcyLq6pfbRFdNuikJNZnLrpcdXGX3RivrUcEKVs3AXXGco6XjX+V10nteaJq6kmkayB5Ev/+aI+sWKCdL+qIkvYnZhDtEkEqlZhAUEzcxex/y9UuJDa/zfinY+Gg7HP0w/bz67tSKXTRRntBOC+70ay/PzvCZC0Ts+7xSmMiG4aW2rqnZAiZsrWZwpTASkoN/+86MeB/zDLpoxKUi2thQZyDNdtRzsL7JEdfT82ZG6p2JUdWWsiWTtJ33uTkapXX/Nds1ipVpxa9L2ZoVXXRIe5vrMj6gcm7pMBo1r1zqQWfE1wXdYZVMnIxVQU+7pakXMHAiPXDlRzajF2k0hFEwg41dnl4pSyb8euqN9FAzEF44aNtiOf59gPtxzhbprNVn7NTBnQ81RBkXhFWMr5hV9Giuj9sCD9uLpwmoqSUt2icGlxnUpCIIMPbDghdjcyu5Cb8UJnPs1geIJvT/zjrxNzYdMFtzWXCBoo/SriJCE720CYv4zVYy6tLOSKVWWlSfytDDQubel2d7+Uts1q1pw='
  file: "$TRAVIS_XCODE_SCHEME.framework.zip"
  on:
    tags: true
git:
  depth: false
